baseURL = 'https://cetyler.github.io/'
languageCode = 'en-us'
title = 'Christopher Tyler'

theme = 'hextra'

sectionPagesMenu = 'main'

enableRobotsTXT = true
enableGitInfo = true
defaultContentLanguage = "en"

[[menu.main]]
  name = 'Search'
  [menu.main.params]
    type = "search"

[params]
  goatcounter = "badc0unt45"

[params.footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = 'normal'

[params.blog.list]
  displayTags = true
  # date | lastmod | publishDate | title | weight
  sortBy = 'date'
  sortOrder = 'desc' # or "asc"

[params.comments]
  enable = false
  type = "giscus"

  [params.comments.giscus]
    repo = "cetyler/cetyler.github.io"
    repoID = "R_kgDOMn2Qrg"
    category = "Articles"
    categoryID = "DIC_kwDOMn2Qrs4CiBFr"
    mapping = "title"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 80

[taxonomies]
  tag = "tags"
  series = "series"

[languages.en]
  languageName = "English"
  weight = 1
  title = "Christopher Tyler"

