baseURL = 'https://cetyler.github.io/'
languageCode = 'en-us'
title = 'Christopher Tyler'

theme = 'hextra'

sectionPagesMenu = 'main'

enableRobotsTXT = true
enableGitInfo = true

[[menu.main]]
	name = 'Search'
	[params]
		type = 'search'
