baseURL = 'https://cetyler.github.io/'
languageCode = 'en-us'
title = 'Christopher Tyler'

theme = 'hextra'

sectionPagesMenu = 'main'

enableRobotsTXT = true
enableGitInfo = true


[[menu.main]]
	name = 'Search'
	[menu.main.params]
		type = "search"

[footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true
    width = 'normal'

[[blog.list]]
    displayTags = true
    # date | lastmod | publishDate | title | weight
    sortBy = 'date'
    sortOrder = 'desc' # or "asc"
