baseURL = 'https://cetyler.github.io/'
languageCode = 'en-us'
title = 'Christopher Tyler'

theme = 'hextra'

sectionPagesMenu = 'main'

enableRobotsTXT = true
enableGitInfo = true
defaultContentLanguage = "en"

[[menu.main]]
  name = 'Search'
  [menu.main.params]
    type = "search"

[params]
  #CODE für den Online Service, der bei Registrierung zum Tracking angegeben wurde (leer = deaktiviert, auch leer für self-hosted!)
  GoatCounter_ID = "badc0unter45"
  #
  # nur bei self-hosted die folgenden Werte setzen (sonst leer lassen!)
  # es ist möglich nur GountCounter_SRC zu setzten, wenn das count.js selbst gehostet wird.
  #URL des Endpoints wo das Script /count aufruft (bsp: "https://count.example.com", /count wird immer angehängt!)
  GoatCounter_URL = ""
  #Source für das Script Tag von dem count.js geladen wird (ohne http/https, mit Dateiname, bsp: "count.example.com/count.js", default = GoatCount_URL, /count.js wird immer angehängt!)
  GoatCounter_SRC = ""

[params.footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = 'normal'

[params.blog.list]
  displayTags = true
  # date | lastmod | publishDate | title | weight
  sortBy = 'date'
  sortOrder = 'desc' # or "asc"

[params.comments]
  enable = false
  type = "giscus"

  [params.comments.giscus]
    repo = "cetyler/cetyler.github.io"
    repoID = "R_kgDOMn2Qrg"
    category = "Articles"
    categoryID = "DIC_kwDOMn2Qrs4CiBFr"
    mapping = "title"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 80

[taxonomies]
  tag = "tags"
  series = "series"

[languages.en]
  languageName = "English"
  weight = 1
  title = "Christopher Tyler"

