baseURL = 'https://cetyler.github.io/'
languageCode = 'en-us'
title = 'Christopher Tyler'

theme = 'hextra'

sectionPagesMenu = 'main'

enableRobotsTXT = true
enableGitInfo = true


[[menu.main]]
  name = 'Search'
  [menu.main.params]
    type = "search"

[params.footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = 'normal'

[params.blog.list]
  displayTags = true
  # date | lastmod | publishDate | title | weight
  sortBy = 'date'
  sortOrder = 'desc' # or "asc"

[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 80

[taxonomies]
  tag = "tags"
  series = "series"
